openapi: 3.0.0
info:
  title: Homebrew API
  description: Returns a list and details for available breweries in the USA.
  version: 1.0.0

paths:
  /breweries:
    get:
      tags:
        - Brewery
      summary: Returns a list of available breweries.
      description: Returns a list of available breweries.
      operationId: getBreweries
      parameters:
        - name: name
          in: query
          required: false
          description: Filters breweries by their name.
          schema:
            type: string
        - name: city
          in: query
          required: false
          description: Filters breweries by the city they are located in.
          schema:
            type: string
        - name: state
          in: query
          required: false
          description: Filters breweries by the state they are located in.
          schema:
            type: string
      responses:
        200:
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: ./BreweryList.yaml
        default:
          description: JSON Problem response.
          content:
            application/problem+json:
              schema:
                $ref: ./ProblemDetails.yaml

  /breweries/{id}:
    get:
      tags:
        - Brewery
      summary: Returns a list of available breweries.
      description: Returns a list of available breweries.
      operationId: getBreweryDetails
      parameters:
        - name: id
          in: path
          required: true
          description: The brewery ID.
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: ./Brewery.yaml
        default:
          description: A default response for common HTTP error codes such as 400, 500.
          content:
            application/problem+json:
              schema:
                $ref: ./ProblemDetails.yaml